t = int(input("Введите значение t: "))
v = int(input("Введите значение v: "))
x = int(input("Введите значение x: "))
y = int(input("Введите значение y: "))
print('5 10   100', t, '  x 25')
print(" 7 см   ")