#а)
x = float(input("Введите x: "))
y = float(input("Введите y: "))
in_area = (2 < x < float('inf')) and (2 < y < float('inf'))
print(f"Точка принадлежит области I?", in_area)
#b)
x = float(input("Введите x: "))
y = float(input("Введите y: "))
in_area = (-2 < x < float('-inf')) and (-4 < y < float('-inf'))
print(f"Точка принадлежит области I?", in_area)